#pragma once
//함수 원형
void CPPBasic();
void Variable();
void Calculation();
void Increment();
void CompareBasic();
void Logical();
void IfFunction01();
void IfFunctionEx02();
void IfFunctionEx03();
void IfFunctionEx04();
void SwitchEx();
void SwitchToIf();
void ForFunctionDesc();
void ForFunctionEx01();
void ForFunctionEx02();
void WhileFunctionDesc();
void WhileFunctionEx01();
void WhileFunctionEx02();