#pragma once
//함수 원형
void CPPBasic();
void Variable();
void Calculation();
void Increment();
void CompareBasic();
void Logical();
void IfFunction01();
void IfFunctionEx02();
void IfFunctionEx03();
void IfFunctionEx04();
void SwitchEx();
void SwitchToIf();
void ForFunctionDesc();
void ForFunctionEx01();
void ForFunctionEx02();
void WhileFunctionDesc();
void WhileFunctionEx01();
void WhileFunctionEx02();
void ParameterFunction(int param1, int param2);
int ReturnFunction();
int ParamReturn(int param1, int param2);
void Sum();
void PrintArray();
void SumArray();
char GradeCalculate(int Score);
void ProcessGrade();
void StringArray();
void PrintArray(int Arr[], int Size);
void BubbleSort();
void MultiArray();
void DefineStructure();
void StructureArray();
void Enumeration();
void CheckOddEven();
void HomeWork01();
void PrintEven();
void CheckGrade();
void FindYourNumber();
void ArraySum();
void FindArrayMinMax();
void SortArray();
void ReverseArray();
int Absolute(int Num);
void Average();